spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/ORCLPDB1
    username: VIP
    password: VIP
    hikari:
      auto-commit: true
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format-sql: true
      show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: heungjae213@gmail.com
    password: skzsfdulumljolyx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분
  ai:
    openai:
      api-key: sk-proj-AwM7STEP6l3XVzKMBWmpT3BlbkFJoOcblUWtjRMYg7mNhL36
      model:
        id: gpt-3.5-turbo

sms:
  api-key: NCSEG7E3NDUBHXWY
  api-secret-key: VU4TQ5AA76NAMP0QOBNNVWOAIEM2VFZX
  base-url: https://api.coolsms.co.kr
  sender-number: 01059421803

jwt:
  secret: qwertyuiopasdfghjklzxcvbnm1234567890

external:
  api:
    url: https://apis.data.go.kr/1741000/StanReginCd/getStanReginCdList
    serviceKey: cmGq3xI%2BAImcpfoEo1nk%2Fyy7jSubP6sbD5NvfrPoSZY0hpehkvVKwN7mrUPzsok9N0JuvsJ7Gj6dmaK%2BJ8FV9Q%3D%3D

kakao:
  api:
    key: 428e2ca7e7783779866d930b7bc7b345


chatbot:
  data:
    file:
      path: src/main/resources/bot-data.json